# Generated by Django 4.2.13 on 2024-07-13 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_usermap_user_alter_pin_usermap'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermap',
            name='likes',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=50)),
                ('map_name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userbookmark', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
