# Generated by Django 4.2.13 on 2024-07-14 08:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_usermap_likes_bookmarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermap',
            name='likes',
        ),
        migrations.AddField(
            model_name='usermap',
            name='likes',
            field=models.ManyToManyField(blank=True, default='none', max_length=50, related_name='liked_maps', to=settings.AUTH_USER_MODEL),
        ),
    ]
